{"name": "test02_app_article", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.test03_app.TestApp object at 0x000001C89DE9F2B0>\n\n    def test02_app_article(self):\n        # 1. 调用查询频道下所有文章测试接口\n        r = self.app.api_app_article()\n        try:\n            # 2. 断言\n>           Tool.common_assert(r, status_code=200)\n\nscripts\\test03_app.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tool.tool.Tool'>, response = <Response [401]>, status_code = 200\n\n    @classmethod\n    def common_assert(cls, response, status_code=201):\n        log.info(\"正在调用公共断言方法\")\n        # 断言状态码\n>       assert status_code == response.status_code\nE       AssertionError\n\ntool\\tool.py:23: AssertionError"}, "attachments": [{"name": "log", "source": "2d1e4980-00c5-4d0c-bf90-191b53a4658e-attachment.txt", "type": "text/plain"}], "start": 1612505365208, "stop": 1612505365298, "uuid": "cb8e4048-79cd-4235-af21-3912d33c3e38", "historyId": "1e883c73aac2203ce0282bdde970dda4", "testCaseId": "bf6271faf3a70f81891fa0c87ca1060b", "fullName": "scripts.test03_app.TestApp#test02_app_article", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test03_app"}, {"name": "subSuite", "value": "TestApp"}, {"name": "host", "value": "DESKTOP-0Q83GN5"}, {"name": "thread", "value": "9284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test03_app"}]}